[package]
name = "rust-hash-cracker"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["cargo", "derive"] }
num = "0.4"
rand = "0.8"
num-bigint = { version = "0.4", features = ["rand"] }
itertools = "0.10"